import {Factory} from 'rosie';
import faker from 'faker';

export default new Factory()
  .sequence('id')
  .attr('name', faker.lorem.sentence)
  .attr('due_date', null)
  .attr('description', faker.lorem.sentences)
  .attr('user_id', faker.random.number)
  .attr('created_at', faker.date.past)
  .attr('updated_at', faker.date.recent)
  .attr('allow_offline_payments', null)
  .attr('allow_echeck_payments', null)
  .attr('offline_payment_instructions', faker.lorem.sentences)
  .attr('deleted_at', null)
  .attr('closed_at', null)
  .attr('display_member_list', faker.random.boolean)
  .attr('display_total_collected', faker.random.boolean)
  .attr('processing_preference', 'user')
  .attr('slug', ['name'], name =>
    faker.helpers.slugify(name.toLowerCase().replace('.', ''))
  )
  .attr('collection_method', 'bank_account')
  .attr('reminder_frequency', null)
  .attr('theme_id', null)
  .attr('open_datetime', null)
  .attr('close_datetime', null)
  .attr('payer_identify', null)
  .attr('access_code', null)
  .attr('account_id', faker.random.number)
  .attr('parent_tab_id', null)
  .attr('payments_total', faker.random.number)
  .attr('pending_total', faker.random.number)
  .attr('failed_total', faker.random.number)
  .attr('online_total', faker.random.number)
  .attr('online_confirmed_total', faker.random.number)
  .attr('online_pending_total', faker.random.number)
  .attr('offline_total', faker.random.number)
  .attr('offline_confirmed_total', faker.random.number)
  .attr('offline_pending_total', faker.random.number)
  .attr('total_user_fees', faker.random.number)
  .attr('total_member_fees', faker.random.number)
  .attr('pending_withdrawals', faker.random.number)
  .attr('approved_withdrawals', faker.random.number)
  .attr('total_withdrawals', faker.random.number)
  .attr('requires_pro', faker.random.boolean)
  .attr('withdrawal_balance_available', faker.random.number)
  .attr('folder', null);
